group=dev.scripted
version=1.1.0

# Paper
paperApiVersion=1.21.4-R0.1-SNAPSHOT

# Fabric — see https://fabricmc.net/develop
minecraftVersion=1.21.4
yarnMappings=1.21.4+build.8
loaderVersion=0.16.9
fabricApiVersion=0.114.0+1.21.4
adventurePlatformFabricVersion=5.14.1

# Shared
adventureVersion=4.18.0
snakeyamlVersion=2.2

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
