package org.bukkit.entity;

public enum EntityType {
    PLAYER, VILLAGER, ZOMBIE, SKELETON, CREEPER, ARMOR_STAND, ITEM, ENDER_PEARL, ARROW,
    IRON_GOLEM, SNOW_GOLEM, WANDERING_TRADER, PIG, COW, SHEEP, CHICKEN, WOLF, CAT, ALLAY,
    BLAZE, WITHER_SKELETON, PIGLIN, ENDERMAN, SLIME, MAGMA_CUBE, WITCH, EXPERIENCE_ORB,
    TEXT_DISPLAY, ITEM_DISPLAY, BLOCK_DISPLAY, INTERACTION, HORSE, AXOLOTL, FROG, PANDA, FOX
}
