package org.bukkit;

/** Stub: a representative slice of the vanilla material list. */
public enum Material {

    AIR, STONE, GRANITE, DIORITE, ANDESITE, DEEPSLATE, COBBLESTONE, DIRT, GRASS_BLOCK, PODZOL, SAND,
    GRAVEL, OAK_LOG, BIRCH_LOG, SPRUCE_LOG, DARK_OAK_LOG, OAK_PLANKS, BIRCH_PLANKS, SPRUCE_PLANKS, BEDROCK,
    OBSIDIAN, CRYING_OBSIDIAN, NETHERRACK, END_STONE, GLASS, TINTED_GLASS, GLOWSTONE, SEA_LANTERN,
    WHITE_WOOL, RED_WOOL, GREEN_WOOL, BLUE_WOOL, BLACK_WOOL, YELLOW_WOOL, LIGHT_BLUE_WOOL, LIME_WOOL,
    GRAY_STAINED_GLASS_PANE, BLACK_STAINED_GLASS_PANE, WHITE_STAINED_GLASS_PANE, RED_STAINED_GLASS_PANE,
    GREEN_STAINED_GLASS_PANE, BLUE_STAINED_GLASS_PANE, LIME_STAINED_GLASS_PANE, YELLOW_STAINED_GLASS_PANE,
    LIGHT_BLUE_STAINED_GLASS_PANE, ORANGE_STAINED_GLASS_PANE, PURPLE_STAINED_GLASS_PANE,
    CYAN_STAINED_GLASS_PANE, MAGENTA_STAINED_GLASS_PANE, PINK_STAINED_GLASS_PANE, BROWN_STAINED_GLASS_PANE,
    LIGHT_GRAY_STAINED_GLASS_PANE, CHEST, ENDER_CHEST, TRAPPED_CHEST, BARREL, SHULKER_BOX, HOPPER, DROPPER,
    DISPENSER, FURNACE, CRAFTING_TABLE, ANVIL, DAMAGED_ANVIL, ENCHANTING_TABLE, BREWING_STAND, CAULDRON,
    BEACON, CONDUIT, BOOKSHELF, LECTERN, JUKEBOX, NOTE_BLOCK, BELL, CAMPFIRE, SOUL_CAMPFIRE, LANTERN,
    SOUL_LANTERN, TORCH, REDSTONE_TORCH, REDSTONE_BLOCK, REPEATER, COMPARATOR, OBSERVER, PISTON,
    STICKY_PISTON, LEVER, COMMAND_BLOCK, CHAIN_COMMAND_BLOCK, REPEATING_COMMAND_BLOCK, STRUCTURE_BLOCK,
    BARRIER, LIGHT, SPAWNER, END_PORTAL_FRAME, END_CRYSTAL, DRAGON_EGG, DRAGON_HEAD, RESPAWN_ANCHOR,
    LODESTONE, IRON_DOOR, OAK_DOOR, IRON_BARS, IRON_TRAPDOOR, OAK_TRAPDOOR, OAK_SIGN, OAK_FENCE, COBWEB,
    LADDER, SCAFFOLDING, ICE, PACKED_ICE, BLUE_ICE, SNOW_BLOCK, POWDER_SNOW_BUCKET, MAGMA_BLOCK, SOUL_SAND,
    SOUL_SOIL, HAY_BLOCK, SPONGE, WET_SPONGE, SLIME_BLOCK, HONEY_BLOCK, TNT, COAL_BLOCK, IRON_BLOCK,
    GOLD_BLOCK, DIAMOND_BLOCK, EMERALD_BLOCK, NETHERITE_BLOCK, LAPIS_BLOCK, COAL, CHARCOAL, RAW_IRON,
    RAW_GOLD, IRON_INGOT, GOLD_INGOT, DIAMOND, EMERALD, NETHERITE_INGOT, NETHERITE_SCRAP, LAPIS_LAZULI,
    REDSTONE, QUARTZ, AMETHYST_SHARD, COPPER_INGOT, STICK, STRING, FEATHER, FLINT, LEATHER, PAPER, BOOK,
    WRITABLE_BOOK, WRITTEN_BOOK, ENCHANTED_BOOK, NAME_TAG, LEAD, SADDLE, BUCKET, WATER_BUCKET, LAVA_BUCKET,
    MILK_BUCKET, GLASS_BOTTLE, BONE, BONE_MEAL, BLAZE_ROD, BLAZE_POWDER, GHAST_TEAR, MAGMA_CREAM,
    SLIME_BALL, GUNPOWDER, ENDER_PEARL, ENDER_EYE, NETHER_STAR, TOTEM_OF_UNDYING, PHANTOM_MEMBRANE,
    SHULKER_SHELL, NAUTILUS_SHELL, HEART_OF_THE_SEA, PRISMARINE_SHARD, PRISMARINE_CRYSTALS, SCUTE,
    TURTLE_HELMET, CLOCK, COMPASS, RECOVERY_COMPASS, SPYGLASS, MAP, FILLED_MAP, FIREWORK_ROCKET,
    FIRE_CHARGE, ELYTRA, TRIDENT, SHIELD, BOW, CROSSBOW, ARROW, SPECTRAL_ARROW, TIPPED_ARROW, SNOWBALL,
    EGG, WOODEN_SWORD, STONE_SWORD, IRON_SWORD, GOLDEN_SWORD, DIAMOND_SWORD, NETHERITE_SWORD,
    WOODEN_PICKAXE, STONE_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE,
    WOODEN_AXE, STONE_AXE, IRON_AXE, GOLDEN_AXE, DIAMOND_AXE, NETHERITE_AXE, WOODEN_SHOVEL, STONE_SHOVEL,
    IRON_SHOVEL, GOLDEN_SHOVEL, DIAMOND_SHOVEL, NETHERITE_SHOVEL, WOODEN_HOE, STONE_HOE, IRON_HOE,
    GOLDEN_HOE, DIAMOND_HOE, NETHERITE_HOE, SHEARS, FLINT_AND_STEEL, FISHING_ROD, CARROT_ON_A_STICK, BRUSH,
    LEATHER_HELMET, LEATHER_CHESTPLATE, LEATHER_LEGGINGS, LEATHER_BOOTS, CHAINMAIL_HELMET,
    CHAINMAIL_CHESTPLATE, CHAINMAIL_LEGGINGS, CHAINMAIL_BOOTS, IRON_HELMET, IRON_CHESTPLATE, IRON_LEGGINGS,
    IRON_BOOTS, GOLDEN_HELMET, GOLDEN_CHESTPLATE, GOLDEN_LEGGINGS, GOLDEN_BOOTS, DIAMOND_HELMET,
    DIAMOND_CHESTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS, NETHERITE_HELMET, NETHERITE_CHESTPLATE,
    NETHERITE_LEGGINGS, NETHERITE_BOOTS, APPLE, GOLDEN_APPLE, ENCHANTED_GOLDEN_APPLE, BREAD, COOKED_BEEF,
    BEEF, COOKED_PORKCHOP, PORKCHOP, COOKED_CHICKEN, CHICKEN, COOKED_MUTTON, MUTTON, COOKED_COD, COD,
    COOKED_SALMON, SALMON, CARROT, GOLDEN_CARROT, POTATO, BAKED_POTATO, POISONOUS_POTATO, BEETROOT,
    MELON_SLICE, PUMPKIN_PIE, COOKIE, CAKE, SWEET_BERRIES, GLOW_BERRIES, CHORUS_FRUIT, DRIED_KELP,
    ROTTEN_FLESH, SPIDER_EYE, FERMENTED_SPIDER_EYE, SUGAR, SUGAR_CANE, WHEAT, WHEAT_SEEDS, NETHER_WART,
    POTION, SPLASH_POTION, LINGERING_POTION, EXPERIENCE_BOTTLE, PLAYER_HEAD, ZOMBIE_HEAD, SKELETON_SKULL,
    WITHER_SKELETON_SKULL, CREEPER_HEAD, PIGLIN_HEAD, VILLAGER_SPAWN_EGG, ZOMBIE_SPAWN_EGG,
    CREEPER_SPAWN_EGG, ARMOR_STAND, ITEM_FRAME, GLOW_ITEM_FRAME, PAINTING, FLOWER_POT, ROSE_BUSH,
    SUNFLOWER, DANDELION, POPPY, OXEYE_DAISY, LILY_PAD, WHITE_DYE, RED_DYE, GREEN_DYE, BLUE_DYE, BLACK_DYE,
    YELLOW_DYE, LIME_DYE, ORANGE_DYE, PURPLE_DYE, CYAN_DYE, MAGENTA_DYE, PINK_DYE, BROWN_DYE, GRAY_DYE,
    LIGHT_GRAY_DYE, LIGHT_BLUE_DYE, BLACK_BANNER, WHITE_BANNER, RED_BANNER, GREEN_BANNER, BLUE_BANNER,
    MUSIC_DISC_CAT, MUSIC_DISC_PIGSTEP, DISC_FRAGMENT_5, GOAT_HORN, ECHO_SHARD, SCULK, SCULK_SENSOR,
    SCULK_CATALYST, SCULK_SHRIEKER, REINFORCED_DEEPSLATE, AMETHYST_BLOCK, BUDDING_AMETHYST, CALCITE, TUFF,
    SMOOTH_STONE, STONE_BRICKS, DEEPSLATE_BRICKS, POLISHED_BLACKSTONE, BLACKSTONE, BASALT,
    POLISHED_ANDESITE;

    public boolean isAir() { throw new UnsupportedOperationException(); }
    public boolean isBlock() { throw new UnsupportedOperationException(); }
    public boolean isItem() { throw new UnsupportedOperationException(); }
    public boolean isEdible() { throw new UnsupportedOperationException(); }
    public int getMaxDurability() { throw new UnsupportedOperationException(); }
    public int getMaxStackSize() { throw new UnsupportedOperationException(); }
    public static Material matchMaterial(String name) { throw new UnsupportedOperationException(); }
}
