package org.bukkit;

public enum Particle {
    FLAME, SMOKE, LARGE_SMOKE, EXPLOSION, EXPLOSION_EMITTER, CLOUD, CRIT,
    ENCHANTED_HIT, PORTAL, END_ROD, DRAGON_BREATH, HAPPY_VILLAGER, ANGRY_VILLAGER,
    HEART, SOUL_FIRE_FLAME, SOUL, ELECTRIC_SPARK, FIREWORK, LAVA, DUST, TOTEM_OF_UNDYING
}
